<?php

namespace RuralBundle\Repository;

/**
 * PropietariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropietariosRepository extends \Doctrine\ORM\EntityRepository
{
}
